[package]
name = "serve"
version = "1.0.0"
edition = "2018"

[dependencies]
rustls = "^0.18"
actix-web = { version = "^3", features = ["rustls"] }
actix-files = "^0"

[[bin]]
name = "serve"
path = "./serve.rs"

[[bin]]
name = "servessl"
path = "./servessl.rs"